# Generated by Django 2.2.6 on 2019-10-26 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_img_url', models.ImageField(upload_to='recipt_img')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt_img_clerk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
