# Generated by Django 2.2.6 on 2019-10-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_img_url', models.ImageField(upload_to='recipt_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt_img', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
