# Generated by Django 2.2.6 on 2019-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0002_auto_20191122_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='recipt',
            name='price',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
