# Generated by Django 2.2.6 on 2019-11-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manage', '0003_auto_20191122_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
